server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/products
    username: postgres
    password: simple123
    initialization-mode: always
  sql:
    init:
      mode: always

resilience4j:
  circuitbreaker:
    instances:
      products-cb:
        failureRateThreshold: 50
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - org.springframework.dao.DataAccessException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.util.concurrent.RejectedExecutionException
logging:
  level:
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    reactor.netty.tcp: DEBUG
    org.springframework.web.reactive: DEBUG